select * from staff
	select * from staff where name ='Chef Zoe'
	select * from staff where name ='Captain Mia'
	select * from staff where name ='Waiter Peter'
	select * from staff where contact='9876501237'
	select * from staff where contact='9876543233'
	select * from staff where stafftype ='cheff'
	select * from staff where stafftype ='waiter'
	select * from staff where bloodgrp='B+'
	select * from staff where bloodgrp='A+'
	select * from staff where address='Kitchen Street, Nagpur'
	select * from staff where address='Cooking Road, Nagpur'
	select * from staff where salary='60000'
	select * from staff where salary='26000'
