select * from customer
    select * from customer where id='7'
	select * from customer where id='6'
	select * from customer where id='1'
	select * from customer where name='Michael Johnson'
	select * from customer where name='Emily Davis'
	select * from customer where name='Olivia Wilson'
	select * from customer where address='404 Birch Way, Nagpur'
	select * from customer where address='202 Cedar Street, Nagpur'
	select * from customer where contact='8765432190'
	select * from customer where contact='9876543210'
	select * from customer where email='michael.j@example.com'
	select * from customer where email='emily.d@example.com'
	select * from customer where customer.restaurantid='2'
	select * from customer where customer.restaurantid='3'
